#! /bin/bash

config=$(cat config.json)
url=$(echo $config | ./jq '.dev.url' | sed "s/\"//g")
url=127.0.0.1:8080
mainPG=bf52ef5d-015e-1000-bdaf-b1a5f8dcf46c
reqUrl="http://$url/nifi-api/flow/process-groups/$mainPG"
resp=$(curl --silent -X GET -H "Connection: keep-alive" $reqUrl)

echo -e "UUID \tNAME"
connections=$(echo $resp | ./jq '.processGroupFlow.flow.connections[]')   
echo $connections | ./jq --raw-output '"\(.id)\t\(.name)"'
echo -e "\n"


