#!/bin/bash

resp=$(curl --silent  'http://localhost:8080/nifi-api/flow/templates' -H 'Cookie: jenkins-timestamper-offset=14400000; _ga=GA1.1.2000614421.1500048204; ACEGI_SECURITY_HASHED_REMEMBER_ME_COOKIE=YWRtaW46MTUwOTQ1OTEwNTEwMjo2ZjgzMjIyODk1N2ViMWY0MGM2MjZmZjM4MGY3MWQ0M2MyMTgzOTBiODI4NjZjZGM2ODllZmNjMWUzOGQxMGUz; JSESSIONID.958f9600=xkwzl96z1l1e28iilj18b67o; _gitlab_session=32d1dafe4ab6d26344c662ae130ca2dd; screenResolution=1440x900' -H 'Accept-Encoding: gzip, deflate, br' -H 'Accept-Language: en-US,en;q=0.8' -H 'User-Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_12_6) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/61.0.3163.100 Safari/537.36' -H 'Accept: application/json, text/javascript, */*; q=0.01' -H 'Referer: http://localhost:8080/nifi/templates?groupId=bf52ef5d-015e-1000-bdaf-b1a5f8dcf46c' -H 'X-Requested-With: XMLHttpRequest' -H 'Connection: keep-alive' --compressed)

echo $resp | jq '.templates[] | {id:.id, name:.template.name}' | jq --raw-output '"\(.id) \t \(.name)"'
